import {userModel} from "../models/userModel.js";
// UserModel => name , email , password , cartData 
import bcrypt from "bcrypt";
import validator from "validator";
import jwt from "jsonwebtoken";

// id: This is the "Data" you want to hide inside the token.
// In your case, it’s the _id generated by MongoDB when a user registers or logs in.
// process.env.JWT_SECRET :-> This is your Private Key. It is a secret string known only to your backend. It acts like a digital wax seal; without it, no one can create a valid token for your website.
const createToken = (id) => {
  return jwt.sign({ id }, process.env.JWT_SECRET);
};

// /api/user/login
// Route for user login
export const loginUser = async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.json({
        success: false,
        message: "Missing fields",
      });
    }

    const user = await userModel.findOne({ email });

    if (!user) {
      return res.json({
        success: false,
        message: "User does not exists",
      });
    }

    const isMatch = await bcrypt.compare(password, user.password);

    if (isMatch) {
      const token = createToken(user._id);
      return res.json({
        success: true,
        token,
        message: "Login successful",
      });
    } else {
      return res.json({
        success: false,
        message: "Invalid credentials",
      });
    }
  } catch (error) {
    return res.json({
      success: false,
      message: error.message,
    });
  }
};

// /api/user/register
// Route for user register
export const registerUser = async (req, res) => {
  try {
    // We will add phone number as well in future 
    // const { phoneNumber, name, email, password } = req.body;
    const { name, email, password } = req.body;

    if (!name || !email || !password) {
      return res.json({
        success: false,
        message: "Missing fields",
      });
    }

    const exists = await userModel.findOne({ email });

    if (exists) {
      return res.json({
        success: false,
        message: "User already exists",
      });
    }

    if (password.length < 8) {
      return res.json({
        success: false,
        message: "Please enter strong password",
      });
    }
    if (!validator.isEmail(email)) {
      return res.json({
        success: false,
        message: "Please enter a valid email",
      });
    }

    // Version/Cost	Characters -> 7	Tells the server how to "read" the hash.
    // Salt (Noise)	Characters -> 22	Prevents "Rainbow Table" (dictionary) attacks.
    // Hash (Cipher) Characters -> 31	The result of the math on your password.
    // Total String	Characters ->60	What you see in your User Model.
    // 10 means 2^10 or (1,024) rounds of processing.

    const salt = await bcrypt.genSalt(10); 
    const hashedPassword = await bcrypt.hash(password, salt);

    const newUser = new userModel({
      name,
      email,
      password: hashedPassword,
    });

    const user = await newUser.save();

    const token = createToken(user._id);

    return res.json({
      success: true,
      token,
      message: "Register successful",
    });
  } catch (error) {
    return res.json({
      success: false,
      message: error.message,
    });
  }
};

// /api/user/admin
// Route for admin login
export const adminLogin = async (req, res) => {
  try {
    const { email, password } = req.body;

    if(email === process.env.ADMIN_EMAIL &&
      password === process.env.ADMIN_PASSWORD){
      // In Professional app, we generally don't put the password inside the token
      const token = jwt.sign(email + password, process.env.JWT_SECRET);
      return res.json({
        success: true,
        token,
      });
    } else {
      return res.json({
        success: false,
        message: "Invalid credentials",
      });
    }
  } catch (error) {
    return res.json({
      success: false,
      message: error.message,
    });
  }
};