import jwt from "jsonwebtoken";

// id: This is the "Data" you want to hide inside the token.
// In your case, it’s the _id generated by MongoDB when a user registers or logs in.
// process.env.JWT_SECRET :-> This is your Private Key. It is a secret string known only to your backend. It acts like a digital wax seal; without it, no one can create a valid token for your website.

export const createToken = (id) => {
  return jwt.sign({ id }, process.env.JWT_SECRET , { expiresIn: "30d",
  });
};